## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [ ]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8111)
html

## Ejercicio 1: Estimadores

completa la función siguiente para que, dado `X` $\in \mathbb{R}^{n \times m}$, un dataframe de Pandas o un array `numpy` con $m$ columnas y $n$ elementos, devuelva dos vectores $\in \mathbb{R}^m$

- uno con los promedios de cada columna de `X`
- uno con las desviaciones estandar de cada columna de `X`

#### Ejemplo de ejecución

    > d = pd.read_csv("data/data_banknote_authentication.txt.gz")
    > print means_stds(d)
    > print means_stds(d.values)
    
    (array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))
    (array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))

In [ ]:
import pandas as pd
import numpy as np

def means_stds(X):
    # TU CODIGO AQUI
    result = ...
    return result

import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(means_stds))

In [ ]:
# VERIFICA TU CODIGO
d = pd.read_csv("data/data_banknote_authentication.txt.gz")
print means_stds(d)
print means_stds(d.values)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_1 $src1

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_1 $src1

## Ejercicio 2: $\mu$, $\sigma$ por clase

Completa la función siguiente para que, por cada valor distinto de $y$ devuelva una lista de promedios y desviaciones estandar de cada columna de la porción de $X$ correspondiente a cada valor de y.

La función a de devolver dos diccionarios python. Uno con las medias y otro con las desviaciones estandar para cada columna y para cada clave. Cada diccionario tendrá como claves los valores presentes en $y$.

#### Ejecución de ejemplo:

Para el siguiente $X$ e $y$:

          X      y
        ------  ---
        [7, 8]   2
        [1, 9]   1
        [2, 4]   0
        [7, 3]   2
        [8, 8]   1
        [6, 6]   1
        [8, 0]   0
        [6, 9]   1
        [3, 5]   0
        [1, 8]   1

La salida ha de ser:

    > m,s = means_stds_perclass(X,y)
    > print "means", means
    > print "stds ", stds
    
    means {0: array([ 4.33333333,  3.        ]), 1: array([ 4.4,  8. ]), 2: array([ 7. ,  5.5])}
    stds  {0: array([ 2.62466929,  2.1602469 ]), 1: array([ 2.87054002,  1.09544512]), 2: array([ 0. ,  2.5])}

In [ ]:
def means_stds_perclass(X,y):
    # TU CODIGO AQUI
    means = ...
    stds  = ...
    return means, stds

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(means_stds_perclass))

In [ ]:
# VERIFICA TU CODIGO
X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
m,s = means_stds_perclass(X,y)
print "means", means
print "stds ", stds

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_2 $src2

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_2 $src2

## Ejercicio 3: Probabilidad conjunta para una clase

completa la función siguiente para que dado

- $X \in \mathbb{R}^{n\times m}$ = $\{ x_1, ..., x_n\}$, con $x_i \in \mathbb{R}^m$ = $\{x_{i,1},...,x_{i,m}\}$
- $m \in \mathbb{R}^m$ un vector con un $\mu$ para cada columna de $X$
- $s \in \mathbb{R}^m$ un vector con un $\sigma$ para cada columna de $X$

devuelva un vector $P \in\mathbb{R}^{n}$ = $\{p_1,...,p_n\}$

de forma que:

$$p_i = \prod_{k=1}^m P_{\mu_k,\sigma_k}(x_{i,k})$$

en donde

$P_{\mu_k,\sigma_k}(x_{i,k})$ es la probabilidad de $x_{i,k}$ según una distribución normal con media $\mu_k$ y desviación estándar $\sigma_k$

El resultado ha de ser un array numpy

#### Ejecución de ejemplo

Para $X$ como en el ejemplo del ejercicio anterior y $m=[4,5]$ y $s=[4,2]$ el resultado debería de ser el siguiente:

    > prob(X, m, s)

    array([ 0.00487532,  0.00203234,  0.01549375,  0.00910831,  0.00391743,
            0.01549375,  0.00053017,  0.00237604,  0.01928228,  0.00487532])
            
**Sugerencia**: usa el método `pdf` de [`scipy.stats.norm`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html) para calcular $P_{\mu_k,\sigma_k}(x_{i,k})$

In [ ]:
def prob(X, m, s):
    import scipy.stats as stats
    
    # TU CODIGO AQUI
    result = ...
    
    return result

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(prob))

In [ ]:
X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
m = np.r_[4,5]
s = np.r_[4,2]
prob(X, m, s)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_3 $src3

## Ejercicio 4: Cálculo de la proporcion de elementos de cada clase

Completa la función siguiente para que, dado un $y$, devuelva un diccionario con la proporcion de elementos existentes para cada valor distinto de $y$

#### Ejecución de ejemplo

    > y = [2 1 0 2 1 1 0 1 0 1]
    > props(y)
    
    {0:0.3, 1:0.5, 2:0.2}

In [ ]:
def props(y):
    # TU CODIGO AQUI
    result = ...
    return result

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(props))

In [ ]:
# VERIFICA TU CODIGO
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
print props(y)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_4 $src4

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_4 $src4

## Ejercicio 5: Clase API sklearn

ensambla las funciones de los ejercicios anteriores en una clase conforme al API de machine learning de sklearn según se describe en el código siguiente.

#### Ejecución de ejemplo

El siguiente código

    > X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
    > y = np.array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

    > b = Bayes()
    > b.fit(X,y)
    > print b.predict(X)
    > print b.score(X,y)
    
debe de arrojar el siguiente resultado

    [1 1 0 0 1 1 0 1 1 1]
    0.7  

In [ ]:
def Bayes(**args): # hack for inspect to work with classes
    from scipy.optimize import minimize
    import numpy as np
    
    class Bayes_class:
        def fit(self, X, y):
            
            # TU CODIGO AQUI
            self.means = ...
            self.stds  = ...
            self.props = ...

        def predict(self, X):
            
            # TU CODIGO AQUI
            # usa el código del ejercicio 4 para elegir, para cada fila de X, 
            # la clase que mas probabilidad tenga.
            
            predictions = ...
            
            return predictions
                
        def score(self, X, y):
            return np.mean(y==self.predict(X))
        
    return Bayes_class(**args)

import urllib, inspect
src5 = urllib.quote_plus(inspect.getsource(Bayes))

In [ ]:
# VERIFICA TU CODIGO

X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

b = Bayes()
b.fit(X,y)
print "mi codigo"
print b.predict(X)
print b.score(X,y)

from sklearn.naive_bayes import GaussianNB
g = GaussianNB()
g.fit(X,y)
print "\nsklearn"
print g.predict(X)
print g.score(X,y)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_5 $src5

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_5 $src5